name: firebase_messaging_example
description: Demonstrates how to use the firebase_messaging plugin.

dependencies:
  firebase_analytics: any
  flutter:
    sdk: flutter
  firebase_messaging:
    path: ../
  firebase_core: ^0.4.0
  flutter_local_notifications: ^1.3.0
  rxdart: ^0.22.6

dev_dependencies:
  pedantic: ^1.8.0
  flutter_test:
    sdk: flutter
  e2e: ^0.2.1
  flutter_driver:
    sdk: flutter
  test: any

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/3x/
